[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_projects = "9HhY4MdAGfRychTsnhGXbfEmXJ4vzjboKS26aduQcf5i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/satya0111/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
nft-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-nfts.ts"
